# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quoted_by',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
